= Setup
include::_attributes.adoc[]

[#prerequisite]
== Prerequisite CLI tools

include::https://raw.githubusercontent.com/redhat-developer-demos/rhd-tutorial-common/master/prerequisites-kubernetes.adoc[]
|`Kafkacat`
|https://github.com/edenhill/kafkacat[Download] or `brew install kafkacat`
|https://github.com/edenhill/kafkacat[Download]
|https://github.com/edenhill/kafkacat[Download]

|`Kstreamscat`
|https://github.com/lordofthejars/kstreamscat/releases/download/v0.0.1/kstreamscat.jar[Download]
|https://github.com/lordofthejars/kstreamscat/releases/download/v0.0.1/kstreamscat.jar[Download]
|https://github.com/lordofthejars/kstreamscat/releases/download/v0.0.1/kstreamscat.jar[Download]

|`Java 11`
|https://adoptopenjdk.net/[Download]
|https://adoptopenjdk.net/[Download]
|https://adoptopenjdk.net/[Download]

IMPORTANT: An alternative for running `kcat` is to use the following Docker command and image  `docker run -it --network=host edenhill/kcat:1.7.0 kcat`
|===

include::https://raw.githubusercontent.com/redhat-developer-demos/rhd-tutorial-common/master/optional-requisites.adoc[]
|===

[#downloadconfiguresources]
== Download & Configure Tutorial Sources

:folder: kafka-tutorial
include::https://raw.githubusercontent.com/redhat-developer-demos/rhd-tutorial-common/master/download-sources.adoc[]

[#kafka]
== Setup Kafka

Assuming you've got https://docs.docker.com/get-docker/[Docker & Docker Compose installed].

[.console-input]
[source, bash-shell]
----
cd $TUTORIAL_HOME/apps/it
docker-compose up --remove-orphans
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
...

kafka_1      | [2020-04-27 05:51:56,560] INFO [Transaction Marker Channel Manager 0]: Starting (kafka.coordinator.transaction.TransactionMarkerChannelManager)
kafka_1      | [2020-04-27 05:51:56,561] INFO [TransactionCoordinator id=0] Startup complete. (kafka.coordinator.transaction.TransactionCoordinator)
kafka_1      | [2020-04-27 05:51:56,597] INFO [ExpirationReaper-0-AlterAcls]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
kafka_1      | [2020-04-27 05:51:56,641] INFO [/config/changes-event-process-thread]: Starting (kafka.common.ZkNodeChangeNotificationListener$ChangeEventProcessThread)
kafka_1      | [2020-04-27 05:51:56,656] INFO [SocketServer brokerId=0] Started data-plane processors for 1 acceptors (kafka.network.SocketServer)
kafka_1      | [2020-04-27 05:51:56,666] INFO Kafka version: 2.4.0 (org.apache.kafka.common.utils.AppInfoParser)
kafka_1      | [2020-04-27 05:51:56,666] INFO Kafka commitId: 77a89fcf8d7fa018 (org.apache.kafka.common.utils.AppInfoParser)
kafka_1      | [2020-04-27 05:51:56,667] INFO Kafka startTimeMs: 1587966716657 (org.apache.kafka.common.utils.AppInfoParser)
kafka_1      | [2020-04-27 05:51:56,669] INFO [KafkaServer id=0] started (kafka.server.KafkaServer)
----

Open a new terminal to run Kafka commands:

Verify that Zookeeper and Apache Kafka containers are up and running:

[.console-input]
[source, bash-shell]
----
docker ps
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                                                                    NAMES
5152b0eabe99        strimzi/kafka:0.17.0-kafka-2.4.0   "sh -c 'bin/kafka-se…"   43 seconds ago      Up 42 seconds       0.0.0.0:9092->9092/tcp, 0.0.0.0:29092->29092/tcp                         kafka
e3417f63ac61        strimzi/kafka:0.17.0-kafka-2.4.0   "sh -c 'bin/zookeepe…"   43 seconds ago      Up 43 seconds       0.0.0.0:2181->2181/tcp, 0.0.0.0:2888->2888/tcp, 0.0.0.0:3888->3888/tcp   it_zookeeper_1
----

IMPORTANT: Notice that Kafka container is exposing two ports to outside. The reason is that Kafka requires one port for accessing from host machine, and another one for accessing from Docker host machine. You can find a full explanation of this at xref:08-kafka-listeners.adoc[Kafka Listeners].

Verify that the Kafka cluster is correctly started and configured by running the following command:

[tabs]
====
kcat::
+
--
[.console-input]
[source, bash-shell]
----
kcat -b localhost:9092 -L
----
--
kcat in Docker::
+
--
[.console-input]
[source, bash-shell]
----
docker run -it --network=host edenhill/kcat:1.7.0 kcat -b localhost:29092 -L
----
====



[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Metadata for all topics (from broker 0: localhost:9092/0):
 1 brokers:
  broker 0 at localhost:9092 (controller)
 0 topics:
----



