= Setup
include::_attributes.adoc[]

[#prerequisite]
== Prerequisite CLI tools

include::https://raw.githubusercontent.com/redhat-developer-demos/rhd-tutorial-common/master/prerequisites-kubernetes.adoc[]
|`kcat`
|https://github.com/edenhill/kcat[Download] or `brew install kcat`
|https://github.com/edenhill/kcat[Download]
|https://github.com/edenhill/kcat[Download]

IMPORTANT: An alternative for running `kcat` is to use the following Docker container image https://hub.docker.com/r/edenhill/kcat (documentation see https://github.com/edenhill/kcat#try-it-out-with-docker)

|`Java 11`
|https://adoptium.net/en-GB/temurin/releases/?version=11[Download]
|https://adoptium.net/en-GB/temurin/releases/?version=11[Download]
|https://adoptium.net/en-GB/temurin/releases/?version=11[Download]

|===

include::https://raw.githubusercontent.com/redhat-developer-demos/rhd-tutorial-common/master/optional-requisites.adoc[]

|===

[#downloadconfiguresources]
== Download & Configure Tutorial Sources

:folder: kafka-tutorial
include::https://raw.githubusercontent.com/redhat-developer-demos/rhd-tutorial-common/master/download-sources.adoc[]

[#kafka]
== Run Kafka

Assuming you've got either https://docs.docker.com/get-docker/[Docker (Desktop) & Docker Compose installed] or https://podman-desktop.io/[Podman (Desktop) & Podman Compose installed]


[tabs]
====
Podman::
+
--
[.console-input]
[source, bash-shell]
----
cd $TUTORIAL_HOME/apps/it
podman compose up
----
--
Docker::
+
--
[.console-input]
[source, bash-shell]
----
cd $TUTORIAL_HOME/apps/it
docker compose up
----
--
====

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
...

[2024-05-13 12:46:44,110] INFO [SocketServer listenerType=BROKER, nodeId=1] Enabling request processing. (kafka.network.SocketServer)
[2024-05-13 12:46:44,110] INFO Awaiting socket connections on kafka:9092. (kafka.network.DataPlaneAcceptor)
[2024-05-13 12:46:44,111] INFO Awaiting socket connections on 0.0.0.0:29092. (kafka.network.DataPlaneAcceptor)
[2024-05-13 12:46:44,112] INFO [BrokerServer id=1] Waiting for all of the authorizer futures to be completed (kafka.server.BrokerServer)
[2024-05-13 12:46:44,112] INFO [BrokerServer id=1] Finished waiting for all of the authorizer futures to be completed (kafka.server.BrokerServer)
[2024-05-13 12:46:44,112] INFO [BrokerServer id=1] Waiting for all of the SocketServer Acceptors to be started (kafka.server.BrokerServer)
[2024-05-13 12:46:44,112] INFO [BrokerServer id=1] Finished waiting for all of the SocketServer Acceptors to be started (kafka.server.BrokerServer)
[2024-05-13 12:46:44,112] INFO [BrokerServer id=1] Transition from STARTING to STARTED (kafka.server.BrokerServer)
[2024-05-13 12:46:44,112] INFO Kafka version: 3.7.0 (org.apache.kafka.common.utils.AppInfoParser)
[2024-05-13 12:46:44,112] INFO Kafka commitId: 2ae524ed625438c5 (org.apache.kafka.common.utils.AppInfoParser)
[2024-05-13 12:46:44,112] INFO Kafka startTimeMs: 1715604404112 (org.apache.kafka.common.utils.AppInfoParser)
[2024-05-13 12:46:44,113] INFO [KafkaRaftServer nodeId=1] Kafka Server started (kafka.server.KafkaRaftServer)

----

Open a new terminal to run Kafka commands:

Verify that the Apache Kafka container is up and running:

[tabs]
====
Podman::
+
--
[.console-input]
[source, bash-shell]
----
podman ps
----
[.console-output]
[source,bash,subs="+macros,+attributes"]
----
CONTAINER ID  IMAGE                                     COMMAND               CREATED             STATUS             PORTS                                             NAMES
8558952ed132  quay.io/strimzi/kafka:0.40.0-kafka-3.7.0  sh -c ./bin/kafka...  About a minute ago  Up About a minute  0.0.0.0:9092->9092/tcp, 0.0.0.0:29092->29092/tcp  kafka
----
--
Docker::
+
--
[.console-input]
[source, bash-shell]
----
docker ps
----
[.console-output]
[source,bash,subs="+macros,+attributes"]
----
CONTAINER ID   IMAGE                                      COMMAND                  CREATED         STATUS         PORTS                                              NAMES
0d4bc6ec2ddf   quay.io/strimzi/kafka:0.40.0-kafka-3.7.0  "sh -c ./bin/kafka..."   2 minutes ago   Up 2 minutes   0.0.0.0:9092->9092/tcp, 0.0.0.0:29092->29092/tcp   kafka
----
--
====

IMPORTANT: Notice that the Kafka container is exposing two ports to outside. The reason is that Kafka requires one port for being accessed from your host machine, and another one for being accessed from the Docker host machine. You can find a full explanation of this at xref:08-kafka-listeners.adoc[Kafka Listeners].

Verify that the Kafka cluster is correctly started and configured by running the following command:

[tabs]
====
kcat::
+
--
[.console-input]
[source, bash-shell]
----
kcat -b localhost:29092 -L
----
[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Metadata for all topics (from broker 0: localhost:29092/0):
 1 brokers:
  broker 0 at localhost:29092 (controller)
 0 topics:
----
--
kcat in Podman::
+
--
[.console-input]
[source, bash-shell]
----
podman run --rm -it --network=kafka-tutorial edenhill/kcat:1.7.1 -b kafka:9092 -L
----
[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Metadata for all topics (from broker 1: kafka:9092/1):
 1 brokers:
  broker 1 at kafka:9092 (controller)
 0 topics:
----
--
kcat in Docker::
+
--
[.console-input]
[source, bash-shell]
----
docker run --rm -it --network=kafka-tutorial edenhill/kcat:1.7.1 -b kafka:9092 -L
----
[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Metadata for all topics (from broker 1: kafka:9092/1):
 1 brokers:
  broker 1 at kafka:9092 (controller)
 0 topics:
----
--
====
