= Produces and Consumers
include::_attributes.adoc[]

[#producer]
== What are Producers?

Producers publish messages to a topic at the end of a partition.
By default if a message contains a key, the hashed value of the key is used to decide in which partition the message is stored.
If key is `null`, then a round-robin algorith is used to balance the messages across all partitions.

Kafka guaranttes that all as long as no new partitions are added, elements with the same key wil be stored in the same partition.

If you wish you can also implement a custom partioning strategy to store messages in a specific partition following any kind of business rule.

<<image P-B>>

[#consumer]
== What are Consumers?

Each message published to a topic is delivered to a consumer that is subscribed to that topic.

A consumer can read data from any position of the partition, and internally it is stored as a pointer called `offset`.
In most of the cases, a consumer advances its `offset` lineraly, but it could be in any order, or starting from any given position.

Each consumer belongs to a consumer group.
A consumer group is a list of consumer instances that ensures the scability for processing messages and also fault tolerance.

When a consumer group only contains one consumer, this consumer is responsible of processing all messages of all partitions.

<<image>>

The more consumers you add to a group, each consumer will only receive messages from a subset of the partitions.

<<image>>

As you can see, in fat, what is registered to a topic is the _consumer group_ and not the consumer.
Consumer is "subscribed" to a partition.