= Developing Kafka Streams in Java
include::_attributes.adoc[]

In this example, we are going to develop an example to build a music chart to see the number of times that a song has been played.

There is one service (`player-app`) that it is periodically producing played songs to the `played-songs` topic.
This service is not using Kafka Streams but instead just uses the Kafka producer API under the covers of Smallrye Reactive Messaging for Kafka.

The second service is a Kafka Stream application that joins the `songs` and `played-songs` topics, to get the song name. Also it computes the number of times that each particular song has been played by aggregating the joined records based on the song's id.

include::partial$kafka-up-dc.adoc[]

You need to open 2 terminal windows to run this example, one for each service.

[#player-songs-java]
== Player Service

The producer code is at {github-repo}/{apps-folder}/player-app[Player Service, window=_blank].

[#deploying-player-app]
=== Deploying Player Service

In this case, the Quarkus service is deployed to produce played songs.

You've got different options, using either pre-built container images run with Podman / Docker or building the application and image on your local machine from the sources.

NOTE: Due to the configured Quarkus extension `quarkus-container-image-jib` the container image will be built automatically when you trigger the local build.

In terminal 1, run one of these two options:

[tabs]
====
[Optional] Local Build & Run Podman::
+
--
[.console-input]
[source, bash-shell,subs="+macros,+attributes"]
----
cd $TUTORIAL_HOME/apps/player-app/quarkus/player-app
----
[.console-input]
[source, bash-shell,subs="+macros,+attributes"]
----
./mvnw clean package -DskipTests
----
[.console-input]
[source, bash-shell,subs="+macros,+attributes"]
----
podman run --rm -it --network=kafka-tutorial quay.io/rhdevelopers/kafka-tutorial-player-app-quarkus:v24.05
----
--
[Optional] Local Build & Run Docker::
+
--
[.console-input]
[source, bash-shell,subs="+macros,+attributes"]
----
cd $TUTORIAL_HOME/apps/player-app/quarkus/player-app
----
[.console-input]
[source, bash-shell,subs="+macros,+attributes"]
----
./mvnw clean package -DskipTests
----
[.console-input]
[source, bash-shell,subs="+macros,+attributes"]
----
docker run --rm -it --network=kafka-tutorial quay.io/rhdevelopers/kafka-tutorial-player-app-quarkus:v24.05
----
--
====

[tabs]
====
Pre-built image with Podman::
+
--
[.console-input]
[source, bash-shell,subs="+macros,+attributes"]
----
podman run --rm -it --network=kafka-tutorial quay.io/rhdevelopers/kafka-tutorial-player-app-quarkus:v24.05-xa
----
--
Pre-built image with Docker::
+
--
[.console-input]
[source, bash-shell,subs="+macros,+attributes"]
----
docker run --rm -it --network=kafka-tutorial quay.io/rhdevelopers/kafka-tutorial-player-app-quarkus:v24.05-xa
----
--
====

Console output when running the containerized application looks as follows:

[.console-output]
[source, bash-shell,subs="+macros,+attributes"]
----
...
2024-05-14 06:46:09,940 INFO  [io.sma.rea.mes.kafka] (smallrye-kafka-producer-thread-1) SRMSG18258: Kafka producer kafka-producer-played-songs, connected to Kafka brokers 'kafka:9092', is configured to write records to 'played-songs'
2024-05-14 06:46:10,021 INFO  [org.acm.PlaySongsGenerator] (main) starting to play random songs every 2500 ms
2024-05-14 06:46:10,050 INFO  [org.acm.PlaySongsGenerator] (main) creating song reference data
2024-05-14 06:46:10,123 INFO  [org.acm.PlaySongsGenerator] (executor-thread-1) Played song id 7 (Fox On The Run) for user Sebi
2024-05-14 06:46:10,131 INFO  [org.acm.PlaySongsGenerator] (main) producing -> Song[id=1, name=The Good The Bad And The Ugly, author=Ennio Morricone]
2024-05-14 06:46:10,871 INFO  [org.acm.PlaySongsGenerator] (main) producing -> Song[id=2, name=Believe, author=Cher]
2024-05-14 06:46:10,890 INFO  [org.acm.PlaySongsGenerator] (main) producing -> Song[id=3, name=Still Loving You, author=Scorpions]
2024-05-14 06:46:10,904 INFO  [org.acm.PlaySongsGenerator] (main) producing -> Song[id=4, name=Bohemian Rhapsody, author=Queen]
2024-05-14 06:46:10,906 INFO  [org.acm.PlaySongsGenerator] (main) producing -> Song[id=5, name=Sometimes, author=James]
2024-05-14 06:46:10,908 INFO  [org.acm.PlaySongsGenerator] (main) producing -> Song[id=6, name=Into The Unknown, author=Frozen II]
2024-05-14 06:46:10,909 INFO  [org.acm.PlaySongsGenerator] (main) producing -> Song[id=7, name=Fox On The Run, author=Sweet]
2024-05-14 06:46:10,911 INFO  [org.acm.PlaySongsGenerator] (main) producing -> Song[id=8, name=Perfect, author=Ed Sheeran]
2024-05-14 06:46:10,970 INFO  [io.quarkus] (main) player-app 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.9.5) started in 7.370s.
2024-05-14 06:46:10,972 INFO  [io.quarkus] (main) Profile prod activated.
2024-05-14 06:46:10,973 INFO  [io.quarkus] (main) Installed features: [cdi, kafka-client, messaging, messaging-kafka, smallrye-context-propagation, vertx]
2024-05-14 06:46:11,481 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | kafka-producer-played-songs) [Producer clientId=kafka-producer-played-songs] Error while fetching metadata with correlation id 1 : {played-songs=UNKNOWN_TOPIC_OR_PARTITION}
2024-05-14 06:46:11,481 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | kafka-producer-songs) [Producer clientId=kafka-producer-songs] Error while fetching metadata with correlation id 1 : {songs=UNKNOWN_TOPIC_OR_PARTITION}
2024-05-14 06:46:12,631 INFO  [org.acm.PlaySongsGenerator] (executor-thread-1) Played song id 1 (The Good The Bad And The Ugly) for user Alex
2024-05-14 06:46:15,129 INFO  [org.acm.PlaySongsGenerator] (executor-thread-1) Played song id 3 (Still Loving You) for user Burr
2024-05-14 06:46:17,622 INFO  [org.acm.PlaySongsGenerator] (executor-thread-1) Played song id 2 (Believe) for user Alex
2024-05-14 06:46:20,123 INFO  [org.acm.PlaySongsGenerator] (executor-thread-1) Played song id 5 (Sometimes) for user Edson
2024-05-14 06:46:22,625 INFO  [org.acm.PlaySongsGenerator] (executor-thread-1) Played song id 3 (Still Loving You) for user Edson
...
----

[#music-chart-java]
== Kafka Streams with Java

The KStreams code is at {github-repo}/{apps-folder}/music-chart-app[Music Chart Service, window=_blank].

[#deploying-music-chart]
=== Deploying Music Chart Service

In this case, the Quarkus service makes use of Kafka Streams.

You've got different options, using either pre-built container images run with Podman / Docker or building the application and image on your local machine from the sources.

NOTE: Due to the configured Quarkus extension `quarkus-container-image-jib` the container image will be built automatically when you trigger the local build.

In terminal 2, run one of these two options:

[tabs]
====
[Optional] Local Build & Run Podman::
+
--
[.console-input]
[source, bash-shell,subs="+macros,+attributes"]
----
cd $TUTORIAL_HOME/apps/music-chart-app/quarkus/music-chart-app
----
[.console-input]
[source, bash-shell,subs="+macros,+attributes"]
----
./mvnw clean package -DskipTests
----
[.console-input]
[source, bash-shell,subs="+macros,+attributes"]
----
podman run --rm -it --network=kafka-tutorial quay.io/rhdevelopers/kafka-tutorial-music-chart-app-quarkus:v24.05
----
--
[Optional] Local Build & Run Docker::
+
--
[.console-input]
[source, bash-shell,subs="+macros,+attributes"]
----
cd $TUTORIAL_HOME/apps/music-chart-app/quarkus/music-chart-app
----
[.console-input]
[source, bash-shell,subs="+macros,+attributes"]
----
./mvnw clean package -DskipTests
----
[.console-input]
[source, bash-shell,subs="+macros,+attributes"]
----
docker run --rm -it --network=kafka-tutorial quay.io/rhdevelopers/kafka-tutorial-music-chart-app-quarkus:v24.05
----
--
====

[tabs]
====
Pre-built image with Podman::
+
--
[.console-input]
[source, bash-shell,subs="+macros,+attributes"]
----
podman run --rm -it --network=kafka-tutorial quay.io/rhdevelopers/kafka-tutorial-music-chart-app-quarkus:v24.05-xa
----
--
Pre-built image with Docker::
+
--
[.console-input]
[source, bash-shell,subs="+macros,+attributes"]
----
docker run --rm -it --network=kafka-tutorial quay.io/rhdevelopers/kafka-tutorial-music-chart-app-quarkus:v24.05-xa
----
--
====

Console output when running the containerized application looks as follows:

[.console-output]
[source, bash-shell,subs="+macros,+attributes"]
----
...
2024-05-14 06:56:34,609 INFO  [org.apa.kaf.str.pro.int.StreamThread] (music-chart-7bc6bbdb-fee1-4d18-89f5-6839bd86c580-StreamThread-1) stream-thread [music-chart-7bc6bbdb-fee1-4d18-89f5-6839bd86c580-StreamThread-1] State transition from PARTITIONS_ASSIGNED to RUNNING
2024-05-14 06:56:34,610 INFO  [org.apa.kaf.str.KafkaStreams] (music-chart-7bc6bbdb-fee1-4d18-89f5-6839bd86c580-StreamThread-1) stream-client [music-chart-7bc6bbdb-fee1-4d18-89f5-6839bd86c580] State transition from REBALANCING to RUNNING
2024-05-14 06:56:35,728 INFO  [org.acm.MusicChartTopologyProducer] (music-chart-7bc6bbdb-fee1-4d18-89f5-6839bd86c580-StreamThread-1) music chart updated for song id 7 -> PlayedSong [count=1, songName=Fox On The Run]
2024-05-14 06:56:35,731 INFO  [org.acm.MusicChartTopologyProducer] (music-chart-7bc6bbdb-fee1-4d18-89f5-6839bd86c580-StreamThread-1) music chart updated for song id 8 -> PlayedSong [count=1, songName=Perfect]
2024-05-14 06:56:35,731 INFO  [org.acm.MusicChartTopologyProducer] (music-chart-7bc6bbdb-fee1-4d18-89f5-6839bd86c580-StreamThread-1) music chart updated for song id 1 -> PlayedSong [count=1, songName=The Good The Bad And The Ugly]
2024-05-14 06:56:35,732 INFO  [org.acm.MusicChartTopologyProducer] (music-chart-7bc6bbdb-fee1-4d18-89f5-6839bd86c580-StreamThread-1) music chart updated for song id 5 -> PlayedSong [count=2, songName=Sometimes]
2024-05-14 06:56:35,732 INFO  [org.acm.MusicChartTopologyProducer] (music-chart-7bc6bbdb-fee1-4d18-89f5-6839bd86c580-StreamThread-1) music chart updated for song id 4 -> PlayedSong [count=3, songName=Bohemian Rhapsody]
2024-05-14 06:56:35,733 INFO  [org.acm.MusicChartTopologyProducer] (music-chart-7bc6bbdb-fee1-4d18-89f5-6839bd86c580-StreamThread-1) music chart updated for song id 6 -> PlayedSong [count=3, songName=Into The Unknown]
2024-05-14 06:56:35,733 INFO  [org.acm.MusicChartTopologyProducer] (music-chart-7bc6bbdb-fee1-4d18-89f5-6839bd86c580-StreamThread-1) music chart updated for song id 2 -> PlayedSong [count=3, songName=Believe]
2024-05-14 06:56:36,849 INFO  [org.acm.MusicChartTopologyProducer] (music-chart-7bc6bbdb-fee1-4d18-89f5-6839bd86c580-StreamThread-1) music chart updated for song id 6 -> PlayedSong [count=4, songName=Into The Unknown]
2024-05-14 06:56:38,968 INFO  [org.acm.MusicChartTopologyProducer] (music-chart-7bc6bbdb-fee1-4d18-89f5-6839bd86c580-StreamThread-1) music chart updated for song id 7 -> PlayedSong [count=2, songName=Fox On The Run]
...
----

[#music-chart-result]
=== Music Chart Result

If you inspect the output of Music Chart service, you see how many times a specific song has been played, and every time a new song is played, the respective song counter is updated.

[#kstreams-cleanup]
== Clean Up

Stop both services by typing kbd:[Ctrl + C] in both terminals 1 and 2.

include::partial$kafka-restart.adoc[]
