---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    app.quarkus.io/vcs-url: "https://github.com/lordofthejars/kafka-tutorial.git"
    app.quarkus.io/build-timestamp: "2020-05-07 - 15:38:51 +0000"
    app.quarkus.io/commit-id: "4074464bbd4a3bd3d9f753fa87145fcd5652ddcc"
  labels:
    app.kubernetes.io/name: "kafka-tutorial-song-app"
    app.kubernetes.io/version: "quarkus"
  name: "kafka-tutorial-song-app"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    app.quarkus.io/vcs-url: "https://github.com/lordofthejars/kafka-tutorial.git"
    app.quarkus.io/build-timestamp: "2020-05-07 - 15:38:51 +0000"
    app.quarkus.io/commit-id: "4074464bbd4a3bd3d9f753fa87145fcd5652ddcc"
  labels:
    app.kubernetes.io/name: "kafka-tutorial-song-app"
    app.kubernetes.io/version: "quarkus"
  name: "kafka-tutorial-song-app"
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: "kafka-tutorial-song-app"
    app.kubernetes.io/version: "quarkus"
  type: "LoadBalancer"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    app.quarkus.io/vcs-url: "https://github.com/lordofthejars/kafka-tutorial.git"
    app.quarkus.io/build-timestamp: "2020-05-07 - 15:38:51 +0000"
    app.quarkus.io/commit-id: "4074464bbd4a3bd3d9f753fa87145fcd5652ddcc"
  labels:
    app.kubernetes.io/name: "kafka-tutorial-song-app"
    app.kubernetes.io/version: "quarkus"
  name: "kafka-tutorial-song-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "kafka-tutorial-song-app"
      app.kubernetes.io/version: "quarkus"
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: "https://github.com/lordofthejars/kafka-tutorial.git"
        app.quarkus.io/build-timestamp: "2020-05-07 - 15:38:51 +0000"
        app.quarkus.io/commit-id: "4074464bbd4a3bd3d9f753fa87145fcd5652ddcc"
      labels:
        app.kubernetes.io/name: "kafka-tutorial-song-app"
        app.kubernetes.io/version: "quarkus"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "quay.io/rhdevelopers/kafka-tutorial-song-app:quarkus"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/health/live"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: "kafka-tutorial-song-app"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/health/ready"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
      serviceAccount: "kafka-tutorial-song-app"
