version: '2.1'

services:

  kafka:
    hostname: kafka
    container_name: kafka
    image: quay.io/strimzi/kafka:0.40.0-kafka-3.7.0
    command: [
      "sh", "-c",
      "./bin/kafka-storage.sh format -t $${KAFKA_CLUSTER_ID} -c ./config/kraft/server.properties && ./bin/kafka-server-start.sh ./config/kraft/server.properties --override inter.broker.listener.name=$${KAFKA_INTER_BROKER_LISTENER_NAME} --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} --override listeners=$${KAFKA_LISTENERS} --override controller.listener.names=$${KAFKA_CONTROLLER_LISTENER_NAMES} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override num.partitions=$${KAFKA_NUM_PARTITIONS} --override group.min.session.timeout.ms=$${KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS}"
    ]
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      LOG_DIR: /tmp/logs
      KAFKA_CLUSTER_ID: DIAO2SH9SdGuqBkcKYXtiw
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INSIDE://kafka:9092,DOCKER_OUTSIDE://localhost:29092
      KAFKA_LISTENERS: DOCKER_INSIDE://kafka:9092,DOCKER_OUTSIDE://0.0.0.0:29092,CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INSIDE:PLAINTEXT,DOCKER_OUTSIDE:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INSIDE
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 250
      KAFKA_NUM_PARTITIONS: 1
    networks:
      - demo-network

networks:
  demo-network:
    name: kafka-tutorial